机器学习

### 1.3.机器学习算法分类

| 目标值     | 问题       |
| ---------- | ---------- |
| 类别       | 分类问题   |
| 连续型数据 | 回归问题   |
| 没有目标值 | 无监督学习 |

### 1.4.机器学习开发流程

1. 获取数据
2. 数据处理
3. 特征工程
4. 机器学习算法训练
5. 模型评估

### 1.5.学习框架和资料介绍

明确

(1)算法是核心、数据与计算是基础

(2)找准定位

大部分复杂模型的算法设计都是算法工程师做的,而我们

+ 分析数据
+ 分析具体业务
+ 应用常见算法
+ 特征工程、调参数、优化







## 2.特征工程

### 2.1.数据集

#### 2.1.1.可用数据集

(1)[skit-learn](http://scikit-learn.org/stable/datasets/index.html#datasets)

(2)[kaggle](https://www.kaggle.com/datasets)

(3)[UCI](http://archive.ics.uci.edu/ml/)

#### 2.1.2. sklearn数据集
+ sklearn.datasets
  加载获取流行数据集、数据包含在datasets里

    + load_*()
      获取小规模数据集,数据包含在datasets里
      
    + datasets.fetch_*(data_home=None)
      获取大规模数据集,需要从网络上下载,函数的第一个参数是data_home,表示数据集下载的目录,默认是~/scikit_data/
      
      
1. sklearn.datasets.load_iris()
加载并返回莺尾花的数据集
|名称|数量|
|--|--|
|类别|3|
|特征|4|
|样本数量|150|
|每个类别的数量|50|
2. sklearn.datasets.load_boston()
加载并返回波士顿房价数据集
|名称|数量|
|--|--|
|目标类别|5-50|
|特征|13|
|样本数量|506
3.sklearn 大数据集
+ sklearn.datasets.fetch_20newgroups(data_home=None,subset='train')
     * subset:'train'或者'test,'all',可选,选择要加载的数据集
     * 训练集的"训练",测试集的""测试",两者的"全部"
##### 2.1.3 sklearn数据集的使用
load和fetch返回的数据类型datasets.base.Bunch(继承自字典)
dict["key"]=values
bunch.key=values
键值对描述
 |键|描述|
 |:--|:--|
 |data|特征数据数组,是二位的numpy.ndarray数组|
 |target|标签数组,是n_samples的一维numpy.ndarray数组|
 |DESCR|数据描述|
 |feature_names|特征名,新闻数据,手写数字,回归数据集无序填写|
 |target_names|标签名|

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
def datasets_demo():
    """
    sklearn数据集的使用
    """
    # 获取数据集
    iris = load_iris()
    print("鸢尾花数据集:\n",iris)
    print("查看数据集描述:\n",iris["DESCR"])
    print("查看特征值的名字:\n",iris.feature_names)
    print("查看特征值:\n",iris.data,iris.data.shape)
    
    # 数据划分
    x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.2,random_state=22)
    print("训练集的特征值：\n",x_train,x_train.shape)
    return None 

if __name__ == "__main__":
    # 代码1：sklearn数据集使用
    datasets_demo()

#### 2.1.4. 数据集的划分
机器学习一般的数据集会有分为两个部分：
+ 训练数据集：用于训练，**构建模型**
+ 通过数据：在模型检验时使用，用于**评估模型是否有效**
   测试集20%——30%
数据划分 api
+ sklearn.model_selection.train_test_split(arrays,*options)
    * x数据值特征
    * y数据值特征
    * test_size测试集的大小，一般为float
    * random_state随机数种子,不同的种子会造成不同的随机采样结果.相同的种子采样结果相同
    * return训练集特征值,测试集特征值,训练集目标值,测试集目标值


### 2.2.特征工程
学习目标
 + 目标
    * 了解特征工程在机器学习当中的重要性
    * 知道特征工程的分类

  特征工程是使用专业背景知识和技巧处理数据，使得特征能在机器学习算法上发挥更好的作用的过程

  pandas 数据清洗和数据处理
  sklearn 特征工程

#### 2.2.1.特征抽取
机器学习算法==统计方法==数学公式
文本类型==>数值
类型==>数值

**定义:将任意数据(如文本或图片)转换为可用于机器学习的数字特征**
+ 字典特征值提取(特征离散化)
+ 文本特征提取
+ 图像特征提取(深度学习介绍)

**数据提取API**
```sklearn.feature_extraction```

##### 2.2.1.1 字典特征提取
作用:对字典数据进行特征值化(Vectory 数学:向量  物理:矢量)

+ ```sklearn.feature_extraction.DictVectorizer(sparse=Ture)```**字典特征提取转换器**- 类别 -> one-hot编码
    * ```DictVectorizer.fit_transform(X)```X:字典或者包含字典的迭代器  
        返回值:返回sparse矩阵

    * ```DictVectorizer.inverse_transform(X)```X:array数组或者sparse矩阵 
        返回值:转换之前的数据格式
        
    * ```DictVectorizer.get_feature_names()```
        返回类别名称

矩阵 matrix 二维数组
向量 vector 一维数组
父类：转换器类

**应用场景：**
+ 数据集中特征类别比较多的情况
    1. 将数据集的特征->字典类型
    2. DictVectorizer转化
+ 本身拿到的数据就是字典类型



In [18]:
from sklearn.feature_extraction import DictVectorizer
def dict_demo():
    """
    字典特征抽取
    """
    data = [{'city':'北京','temperature':100},{'city':'上海','temperature':60},{'city':'深圳','temperature':30}]
    # 1.实例化一个转换器类
    transfer=DictVectorizer(sparse=False) # 不填写参数返回稀疏数组

    # 2.调用fit_transform()
    data_new = transfer.fit_transform(data)

    # 打印出的是稀疏矩阵
    print("data_new:\n",data_new)
    print("特征名字:\n",transfer.get_feature_names())
    return None

if __name__ == "__main__":
    dict_demo()

data_new:
 [[  0.   1.   0. 100.]
 [  1.   0.   0.  60.]
 [  0.   0.   1.  30.]]
特征名字:
 ['city=上海', 'city=北京', 'city=深圳', 'temperature']



##### 2.2.1.2.文本特征提取
单词 作为 特征
句子、短语、单词、字母
特征：特征词

+ ``` sklearn.feature_extraction.text.CountVectorizer(stop_words=[])```
     返回词频矩阵
     stop_words 表示停用词，有的时对我们最终分类没有用的词，将会以列表的形式传递给CountVectorize，这种列表叫做停用词表，许多作自然语言处理的机构就会总结
+ ``` CountVectorizer.fit_transform(X)```
     X:文本或者包含文本字符串可迭代对象
     返回值： 返回sparse矩阵
+ ``` CountVectorizer.get_feature_names()```
     返回值： 单词列表
#### 2.2.2.特征预处理
#### 2.2.3.特征降维

In [25]:
from sklearn.feature_extraction.text import  CountVectorizer
def count_demo():
    """
    中文文本特征抽取：CountVectorizer

    """
    data = ["Life is short,i like like python","life is too long,i dislike python"]

    # 1.实例化一个转换器类
    transfer = CountVectorizer( )

    # 2.调用fit_transform 
    data_new = transfer.fit_transform(data)

    print("data_new:\n",data_new.toarray())
  

    print("特征名字：\n",transfer.get_feature_names())

    return None

def count_chinese_demo():
    """
    中文文本特征抽取：CountVectorizer

    """
    data = ["我 爱 北京 天安 门","天安 门 上太阳 升"]

    # 1.实例化一个转换器类
    transfer = CountVectorizer()

    # 2.调用fit_transform 
    data_new = transfer.fit_transform(data)

    print("data_new:\n",data_new.toarray())
  
    print("特征名字：\n",transfer.get_feature_names())

    return None

if __name__=="__main__":
    count_demo()
    count_chinese_demo()

data_new:
 [[0 1 1 2 0 1 1 0]
 [1 1 1 0 1 1 0 1]]
特征名字：
 ['dislike', 'is', 'life', 'like', 'long', 'python', 'short', 'too']
data_new:
 [[0 1 1]
 [1 0 1]]
特征名字：
 ['上太阳', '北京', '天安']


In [22]:
import jieba
from sklearn.feature_extraction.text import CountVectorizer
def cut_word(text):
    """
    @description  :proceed chinese sparating words
    ---------
    @param  : text     
    -------
    @Returns  :text
    -------
    """
    # get generate
    generator=jieba.cut(text)
    
    textlist = list(generator)

    # print(textlist)
    
    #transform to str
    string_text=" ".join(textlist)

    # print(string_text)
    
    # print(type(string_text))
    return string_text

def count_chinese_demo2():
    """
    @description  : chinese content splite automatically
    ---------
    @param  :
    -------
    @Returns  :
    -------
    """

    data = ["统计学作为数据分析的入门知识，非常的重要，作为入门，必须要掌握描述性统计以及里面各类图表的应用场景和理解。",
            "而再深入到，如线性回归，贝叶斯，假设检验等，则是为以后成为高级数据分析师做铺垫，在未来做到建模和预测时。",
            "会用到很多这类知识，同时在未来进阶过程中，学习机器学习的一些经典算法时，也需要这些知识来帮助理解和学习。",
            "Excel作为数据分析的基础，是众多数据分析工具的入门工具，而且它的功能非常的强大，具有非常多的实用性，在快速处理一些数据。",
            "快速出图的时候，非常的灵活，也非常的便捷，其中也有很多的函数，包括max,min,average,find,match,vlookup等。",
            "可以非常灵活的查询数值或者进行统计分析，同时Excel的数据透视表功能也非常的强大，可以快速的选取所需元素进行分析。",
            "非常适合用来做快速的数据清洗，入门门槛低，而且实用性非常强。"]
    data_new = []
    for sent in data:
        data_new.append(cut_word(sent))
    # print(data_new)

    # 1. instantiate a tranfer obj
    transfer = CountVectorizer()

    # 2. call the function of fit_transform()
    worked_data = transfer.fit_transform(data_new)
    print("worked_data:\n",worked_data.toarray())
    print("特征名称：\n",transfer.get_feature_names())
    return None

if __name__ == "__main__":
    count_chinese_demo2()
    cut_word("我爱北京天安门")

worked_data:
 [[0 0 0 0 0 0 0 0 1 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0
  0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0
  0 0 0 1 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 3 0 0
  1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 2 1 0 1 0 0 0 0 0 1 1 0
  1 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 2
  0 0 0 1 0 0 1 0 0 0 0 0 1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 2 0 0 0 0]
 [1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 2 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 2 0 1 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 1 0 1 0 0 1 1